# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  common_config = debug
  devka_physics_config = debug
  devka_graphic_config = debug
  devka_core_config = debug
  devka_editor_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  common_config = release
  devka_physics_config = release
  devka_graphic_config = release
  devka_core_config = release
  devka_editor_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui common devka-physics devka-graphic devka-core devka-editor

.PHONY: all clean help $(PROJECTS) 3rdparty

all: $(PROJECTS)

3rdparty: GLFW ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C devka-graphic/3rdparty/glfw -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C devka-graphic/3rdparty/imgui -f Makefile config=$(ImGui_config)
endif

common:
ifneq (,$(common_config))
	@echo "==== Building common ($(common_config)) ===="
	@${MAKE} --no-print-directory -C common -f Makefile config=$(common_config)
endif

devka-physics: common
ifneq (,$(devka_physics_config))
	@echo "==== Building devka-physics ($(devka_physics_config)) ===="
	@${MAKE} --no-print-directory -C devka-physics -f Makefile config=$(devka_physics_config)
endif

devka-graphic: common GLFW ImGui
ifneq (,$(devka_graphic_config))
	@echo "==== Building devka-graphic ($(devka_graphic_config)) ===="
	@${MAKE} --no-print-directory -C devka-graphic -f Makefile config=$(devka_graphic_config)
endif

devka-core: devka-physics devka-graphic
ifneq (,$(devka_core_config))
	@echo "==== Building devka-core ($(devka_core_config)) ===="
	@${MAKE} --no-print-directory -C devka-core -f Makefile config=$(devka_core_config)
endif

devka-editor: common devka-core
ifneq (,$(devka_editor_config))
	@echo "==== Building devka-editor ($(devka_editor_config)) ===="
	@${MAKE} --no-print-directory -C devka-editor -f Makefile config=$(devka_editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C devka-graphic/3rdparty/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C devka-graphic/3rdparty/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C common -f Makefile clean
	@${MAKE} --no-print-directory -C devka-physics -f Makefile clean
	@${MAKE} --no-print-directory -C devka-graphic -f Makefile clean
	@${MAKE} --no-print-directory -C devka-core -f Makefile clean
	@${MAKE} --no-print-directory -C devka-editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   common"
	@echo "   devka-physics"
	@echo "   devka-graphic"
	@echo "   devka-core"
	@echo "   devka-editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"